site_name: Formazione tecnica - Edge N / N+
site_url: https://github.com/ivanrobuschi-custom/corso-tecnico-edge-n.git
site_author: Ivan Robuschi
theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags

copyright: Copyright Custom S.p.A 2026


nav:
  - Serie Edge: index.md
  - Infrastruttura Hardware:
      - Edge N+: hardware.md
      - Edge N: hardwareedgen.md
  - Normativa fiscale:
      - Introduzione: normativa11.md
      - Chiusure ore 24: chiusuragiornaliera.md
      - Periodo d'inattività: periodoinattivita.md
      - Disallineamenti Ade:
          - disallineamento.md
          - Errore Xml 409: errore409.md
  - Connessioni di rete: 
        - Schema connessione interna: schemadiconnessione.md
        - Metodi di connessione ad internet: 
            - Connessione Ethernet: connessione_eth.md
            - Connessione WiFi: connessione_wifi.md
            - Connessione Sim dati: simdati.md
  - Procedure rt:
    - Messa in servizio: prefmessa.md
    - Disattivazione: disattivazione.md
    - Dismissione: dismissione.md
  - Troubleshooting: 
    - Reset 1,3: reset.md
  - Configurazione KeepUp Smart:

   
