site_name: Formazione tecnica - Edge N / N+
site_url: https://github.com/ivanrobuschi-custom/corso-tecnico-edge-n.git
theme:
  name: material
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - toc.integrate

copyright: '<a href="hardwareedgen/">Edge N</a> | <a href="hardware/">Edge N+</a>'


nav:
  - Serie Edge: index.md
  - Infrastruttura Hardware:
      - Edge N+: hardware.md
      - Edge N: hardwareedgen.md
  - Normativa fiscale: normativa11.md
  - Messa in servizio: messainservizio.md